default_language_version:
    python: python3.9
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.3.4'
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format      
