default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.3.4"
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0" # add version here
    hooks:
      - id: poetry-check