[tool.poetry]
name = "cloud-tasks-emulator"
version = "0.1.0"
description = "Local emulator for Google Cloud Tasks"
authors = ["Pontus Bergkvist <pontus.bergkvist@gmail.com>"]
readme = "README.md"
packages = [{include = "cloud_tasks_emulator"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
redis = "^4.5.4"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.0"
black = "^23.3.0"
ruff = "^0.0.261"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']

[tool.ruff]
line-length = 120
target-version = 'py310'