[tool.poetry]
name = "cloud-tasks-emulator"
version = "1.0.0"
description = "Local emulator for Google Cloud Tasks"
authors = ["Pontus Bergkvist <pontus.bergkvist@gmail.com>"]
readme = "README.md"
packages = [{include = "cloud_tasks_emulator", from ="src"}]


[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.2"
redis = "2.10.6"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.261"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py39']

[tool.ruff]
line-length = 120
target-version = 'py39'